---
db:
  dbname: "postgres"
  host: "$HOST"
  port: "$PORT"
  user: "postgres"
  password: "postgres"
  sslmode: "disable"
session:
  store: "something-very-secret"
  sessionName: "go-simple-web"
  flashName: "go-flash"